parameters:
- name: host
  type: string
- name: client_id
  type: string
- name: client_secret
  type: string

steps:
- script: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
  displayName: 'Install Databricks CLI'

- script: |
    cat << END > ~/.databrickscfg
    [DEFAULT]
    host = ${{ parameters.host }}
    client_id = ${{ parameters.client_id }}
    client_secret = ${{ parameters.client_secret }}
    END
  displayName: 'Set up .databrickscfg file'
