trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: REPO_NAME
  displayName: "Repo to deploy"
  type: string
  values:
  - ""

variables:
- group: databricks-service_principal

steps:
- checkout: git://$(System.TeamProject)/${{ parameters.REPO_NAME }}
- template: cli.yml
  parameters:
    host: $(HOST)
    client_id: $(CLIENT_ID)
    client_secret: $(CLIENT_SECRET)
- script: |
    export DESTINATION="/.../${{ parameters.REPO_NAME }}"
    databricks workspace delete $DESTINATION --recursive
    databricks workspace import-dir . $DESTINATION
  displayName: 'Deploy ${{ parameters.REPO_NAME }}'
