trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: REPO_NAME
  displayName: "Repo to deploy"
  type: string
  values:
  - ""

variables:
- group: databricks-service_principal

steps:
- checkout: git://$(System.TeamProject)/${{ parameters.REPO_NAME }}
- template: cli.yml
  parameters:
    host: $(HOST)
    client_id: $(CLIENT_ID)
    client_secret: $(CLIENT_SECRET)
- script: |
    export DESTINATION="dbfs:/.../${{ parameters.REPO_NAME }}"
    databricks fs rm $DESTINATION --recursive
    databricks fs cp . $DESTINATION --recursive
  displayName: 'Deploy ${{ parameters.REPO_NAME }}'
